// Conditions A to Z: every condition people may look for, including ones that are not among the
// photo tiles on the home page. `href` is a page on this site that explains the condition or its
// treatment; entries without one (`href` omitted) lead to the specialist finder, so nobody meets a
// dead end. `also` holds other words people use. Add a line here and it shows up on /conditions/.

export type AZCondition = { label: string; href?: string; also?: string[] };

export const AZ_CONDITIONS: AZCondition[] = [
  { label: "ADHD (attention deficit hyperactivity disorder)", href: "/adhd-treatment/", also: ["attention", "hyperactive", "restless child"] },
  { label: "Addiction (all types)", href: "/addiction-treatment/", also: ["de-addiction", "rehab", "substance use", "nasha"] },
  { label: "Agoraphobia", also: ["fear of crowds", "fear of leaving home"] },
  { label: "Alcohol addiction", href: "/deaddiction-centre/alcohol-addiction/", also: ["alcoholism", "drinking", "daaru", "alcohol use disorder"] },
  { label: "Alcohol-related liver disease", href: "/liver-cirrhosis/", also: ["cirrhosis", "alcoholic hepatitis", "fatty liver"] },
  { label: "Alzheimer’s disease", href: "/treatment-of-dementia/", also: ["memory loss", "dementia"] },
  { label: "Anger problems", also: ["irritability", "aggression", "short temper"] },
  { label: "Anxiety", href: "/anxiety/", also: ["worry", "panic", "nervousness", "generalised anxiety"] },
  { label: "Autism spectrum disorder", href: "/autism-spectrum-disorder/", also: ["autism", "asd", "developmental delay"] },
  { label: "Binge eating disorder", also: ["overeating", "eating problems"] },
  { label: "Bipolar disorder", href: "/bipolar-disorder-treatment-delhi-gurgaon/", also: ["mood swings", "mania", "manic depression"] },
  { label: "Body dysmorphic disorder", also: ["body image", "appearance worries"] },
  { label: "Borderline personality disorder", href: "/cluster-b-personality-disorders/", also: ["bpd", "unstable relationships"] },
  { label: "Burnout", href: "/counsellor-near-me/", also: ["work stress", "exhaustion"] },
  { label: "Cannabis (marijuana) addiction", href: "/deaddiction-centre/marijuana-treatment/", also: ["ganja", "weed", "bhang"] },
  { label: "Child and teen mental health", href: "/child-psychiatry-hospital-services/", also: ["behaviour problems", "school refusal", "adolescent"] },
  { label: "Cluster A personality disorders", href: "/cluster-a-personality-disorders/", also: ["paranoid", "schizoid", "schizotypal"] },
  { label: "Cluster B personality disorders", href: "/cluster-b-personality-disorders/", also: ["narcissistic", "antisocial", "histrionic"] },
  { label: "Cluster C personality disorders", href: "/cluster-c-personality-disorders/", also: ["avoidant", "dependent", "obsessive-compulsive personality"] },
  { label: "Cocaine addiction", href: "/deaddiction-centre/cocaine-addiction/", also: ["coke"] },
  { label: "Cognitive behavioural therapy (CBT)", href: "/cbt-behavioural-therapy/", also: ["therapy", "talking therapy"] },
  { label: "Conduct problems in children", href: "/child-psychiatry-hospital-services/", also: ["lying", "stealing", "defiant"] },
  { label: "Coming out stress", href: "/lgbtq-support/", also: ["lgbtq", "family pressure"] },
  { label: "Dementia", href: "/treatment-of-dementia/", also: ["memory", "elderly", "old age", "forgetfulness"] },
  { label: "Depression", href: "/depression/", also: ["low mood", "sadness", "hopelessness"] },
  { label: "Digital and gaming addiction", href: "/digital-and-gaming-addiction/", also: ["gaming", "mobile addiction", "screen time", "internet addiction"] },
  { label: "Drug addiction", href: "/drug-addiction-treatment-in-delhi-gurgaon-and-ncr/", also: ["substance abuse", "nasha", "drugs"] },
  { label: "Dual diagnosis", href: "/dual-diagnosis/", also: ["addiction and mental illness together"] },
  { label: "Eating disorders", also: ["anorexia", "bulimia", "weight worries"] },
  { label: "Exam stress", also: ["study pressure", "school stress"] },
  { label: "Fatty liver (alcoholic)", href: "/fatty-liver-disease/" },
  { label: "Gaming addiction", href: "/digital-and-gaming-addiction/", also: ["video games"] },
  { label: "Generalised anxiety disorder", href: "/anxiety/", also: ["gad", "constant worry"] },
  { label: "Grief and loss", also: ["bereavement", "mourning"] },
  { label: "Gender identity concerns", href: "/lgbtq-support/", also: ["transgender", "gender dysphoria", "identity"] },
  { label: "Heroin addiction", href: "/deaddiction-centre/heroin-addiction/", also: ["smack", "brown sugar"] },
  { label: "Insomnia and sleep problems", also: ["cannot sleep", "poor sleep", "sleeplessness"] },
  { label: "LGBTQ+ mental health support", href: "/lgbtq-support/", also: ["gay", "lesbian", "bisexual", "transgender", "queer", "coming out", "gender identity", "sexual orientation", "pride"] },
  { label: "Learning difficulties", href: "/iq-testing/", also: ["dyslexia", "school performance", "iq test"] },
  { label: "Liver cirrhosis", href: "/liver-cirrhosis/" },
  { label: "Marriage and relationship problems", href: "/marriage-counselling/", also: ["couple", "conflict", "divorce"] },
  { label: "Memory loss", href: "/treatment-of-dementia/", also: ["forgetting", "confusion"] },
  { label: "Mood swings", href: "/bipolar-disorder-treatment-delhi-gurgaon/" },
  { label: "Narcissistic personality disorder", href: "/cluster-b-personality-disorders/", also: ["npd"] },
  { label: "Nicotine and smoking", href: "/smoking-cessation/", also: ["tobacco", "cigarettes", "quit smoking"] },
  { label: "Obsessive compulsive disorder (OCD)", href: "/obsessive-compulsive-disorder-treatment/", also: ["ocd", "compulsions", "repeating", "checking", "washing"] },
  { label: "Old age problems", href: "/treatment-of-dementia/", also: ["geriatric", "elderly", "senior"] },
  { label: "Panic attacks", href: "/anxiety/", also: ["panic disorder", "sudden fear"] },
  { label: "Paranoia", href: "/schizophrenia-treatment-delhi-gurgaon-ncr/", also: ["suspicion", "delusions"] },
  { label: "Personality disorders", href: "/treatment-of-personality-disorders/" },
  { label: "Phobias", href: "/blog/phobias-and-their-treatment-by-psychiatrists/", also: ["fear", "specific phobia"] },
  { label: "Postpartum depression", also: ["after childbirth", "new mother", "baby blues"] },
  { label: "Post-traumatic stress disorder (PTSD)", also: ["ptsd", "flashbacks", "trauma"] },
  { label: "Psychosis", href: "/schizophrenia-treatment-delhi-gurgaon-ncr/", also: ["hearing voices", "hallucinations", "delusions"] },
  { label: "Schizophrenia", href: "/schizophrenia-treatment-delhi-gurgaon-ncr/", also: ["psychosis", "voices", "withdrawn"] },
  { label: "Sexual health problems", href: "/sexologist-in-delhi/", also: ["sexual dysfunction", "sexologist", "performance"] },
  { label: "Smoking cessation", href: "/smoking-cessation/" },
  { label: "Social anxiety", href: "/anxiety/", also: ["shyness", "fear of people"] },
  { label: "Stress", href: "/counsellor-near-me/", also: ["tension", "pressure"] },
  { label: "Stroke rehabilitation", href: "/stroke-rehabilitation/", also: ["after stroke"] },
  { label: "Trauma", also: ["abuse", "accident", "distressing event"] },
  { label: "Treatment-resistant depression", href: "/dtms-for-treatment-resistance-depression/", also: ["dtms", "tms", "depression not improving"] },
];

export const LETTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");
export const firstLetter = (label: string) => label.replace(/[^A-Za-z]/g, "").charAt(0).toUpperCase();
